project_name: Tofu Testing Project
project_id: playground-tofu-project
location_id: europe-west4

# Ap Engine specific configuration
app_engine_location_id: europe-west

# Used by the Workload Identity Provider to assert the request is coming from the correct source.
repo_name: EnlitHamster/example-appengine

# GCP APIs required for by the stack
apis:
- iap.googleapis.com
- appengine.googleapis.com
- appenginereporting.googleapis.com
- cloudbuild.googleapis.com
- cloudtasks.googleapis.com
- sql-component.googleapis.com
- sqladmin.googleapis.com
- logging.googleapis.com
- secretmanager.googleapis.com
- storage-component.googleapis.com
- storage.googleapis.com

# OpenTofu service account configuration.
service_account_name: opentofu
service_account_key_filename: opentofu-playground-tofu-project-key.json
service_account_roles:
- roles/iam.serviceAccountAdmin
- roles/iam.workloadIdentityPoolAdmin
- roles/secretmanager.admin
- roles/serviceusage.serviceUsageAdmin
- roles/storage.admin